Data Analysis Assumptions
=======================================================================================================================
The bridges data has one numeric column, length, and no obviously impossible values. The length depends heavily on material and type. The stronger the material the greater the length of the bridge is a plausible assumption. Also, the type of bridge tracks with the advancement on design technology and on design year. It is plausible to assume that the later the bridge was built, the greater the length of the bridge. We see that technology is also advancing with time, and that would reinforce the assumption that the later the bridge was built, the greater the length of the bridge.

Cleaning Log I

Import libraries (panda & seaborn)

load .csv file containing data and store in variable, 'df'

In [31]:
import pandas as pd
import seaborn as sns

df = pd.read_csv("bridges.csv")

Cleaning Log II

dispay the number of rows & columns, given by the .shape() function

In [32]:
df.shape

(108, 13)

Cleaning Log III

dispay the first 10 rows, given by the .head(10) function

In [33]:
df.head(10)

,Id,river,location,erected,purpose,length,lanes,clear-g,t-or-d,material,span,rel-l,type
0,E1,M,3.0,1818,HIGHWAY,NaN,2.0,N,THROUGH,WOOD,SHORT,S,WOOD
1,E2,A,25.0,1819,HIGHWAY,1037.0,2.0,N,THROUGH,WOOD,SHORT,S,WOOD
2,E3,A,39.0,1829,AQUEDUCT,NaN,1.0,N,THROUGH,WOOD,NaN,S,WOOD
3,E5,A,29.0,1837,HIGHWAY,1000.0,2.0,N,THROUGH,WOOD,SHORT,S,WOOD
4,E6,M,23.0,1838,HIGHWAY,NaN,2.0,N,THROUGH,WOOD,NaN,S,WOOD
5,E7,A,27.0,1840,HIGHWAY,990.0,2.0,N,THROUGH,WOOD,MEDIUM,S,WOOD
6,E8,A,28.0,1844,AQUEDUCT,1000.0,1.0,N,THROUGH,IRON,SHORT,S,SUSPEN
7,E9,M,3.0,1846,HIGHWAY,1500.0,2.0,N,THROUGH,IRON,SHORT,S,SUSPEN
8,E10,A,39.0,1848,AQUEDUCT,NaN,1.0,N,DECK,WOOD,NaN,S,WOOD
9,E11,A,29.0,1851,HIGHWAY,1000.0,2.0,N,THROUGH,WOOD,MEDIUM,S,WOOD

Cleaning Log IV

dispay the last 10 rows, given by the .tail(10) function

In [34]:
df.tail(10)

,Id,river,location,erected,purpose,length,lanes,clear-g,t-or-d,material,span,rel-l,type
98,E82,O,42.0,1955,HIGHWAY,804.0,NaN,G,THROUGH,STEEL,NaN,F,SIMPLE-T
99,E102,O,47.0,1959,HIGHWAY,1700.0,2.0,G,THROUGH,STEEL,LONG,F,CONT-T
100,E83,M,1.0,1959,HIGHWAY,1000.0,6.0,G,THROUGH,STEEL,LONG,F,ARCH
101,E86,A,33.0,1961,HIGHWAY,980.0,4.0,G,DECK,STEEL,MEDIUM,S-F,CONT-T
102,E85,M,9.0,1962,HIGHWAY,2213.0,4.0,G,DECK,STEEL,LONG,F,CONT-T
103,E84,A,24.0,1969,HIGHWAY,870.0,6.0,G,THROUGH,STEEL,MEDIUM,F,ARCH
104,E91,O,44.0,1975,HIGHWAY,3756.0,6.0,G,THROUGH,STEEL,LONG,F,ARCH
105,E90,M,7.0,1978,HIGHWAY,950.0,6.0,G,THROUGH,STEEL,LONG,F,ARCH
106,E100,O,43.0,1982,HIGHWAY,NaN,NaN,G,NaN,NaN,NaN,F,NaN
107,E109,A,28.0,1986,HIGHWAY,NaN,NaN,G,NaN,NaN,NaN,F,NaN

Data Review
------------------------------------------------------------------------------------------------------------------------------
There is at least one problems that I can already see in this data:

In the 'length' column of interest, there are several rows that are either blank entries or characters not representing a number. This values is represented by "NaN".

Cleaning Log V

dispay the data types of the columns, given by the .dtypes() function

In [35]:
df.dtypes

Id              str
river           str
location    float64
erected       int64
purpose         str
length      float64
lanes       float64
clear-g         str
t-or-d          str
material        str
span            str
rel-l           str
type            str
dtype: object

Cleaning Log VI

dispay the blank entries of the columns, given by the .isna().sum() function

In [36]:
df.isna().sum()

Id           0
river        0
location     1
erected      0
purpose      0
length      27
lanes       16
clear-g      2
t-or-d       6
material     2
span        16
rel-l        5
type         2
dtype: int64

Data Reveiw
============================================================================================================================
1. Fill the 27 missing 'length' values using the 'median' statistic that resists skewed measure of lengths of the bridges.
2. Print the fill value I used and record the fill value for your cleaning log.
3. I will show that there are 0 missing prices afterwards.

In [37]:
fill_value = df["length"].mean()
print(f'The fill value represented by the mean of the price column is {fill_value}.')
df["length"] = df["length"].fillna(fill_value)
df.isna().sum()

The fill value represented by the mean of the price column is 1567.469135802469.

Id           0
river        0
location     1
erected      0
purpose      0
length       0
lanes       16
clear-g      2
t-or-d       6
material     2
span        16
rel-l        5
type         2
dtype: int64

Cleaning Log VII

Here, I show that there were 0 duplicates in the data frame before the .drop_duplicates() function.

In [38]:
print(df.duplicated().sum())
df = df.drop_duplicates()

0

Cleaning Log VIII

Via the shape() function, I now show the quantity of rows of the data frame are now 50. Same as it has always been even with the data cleaning we have done thus far.

In [39]:
df.shape

(108, 13)

Cleaning Log IX

compute summary statistics usoing the .describe() function.

In [40]:
df.describe()

         location      erected       length      lanes
count  107.000000   108.000000   108.000000  92.000000
mean    25.978505  1905.314815  1567.469136   2.630435
std     13.665871    37.173664   646.337534   1.164657
min      1.000000  1818.000000   804.000000   1.000000
25%     15.500000  1884.000000  1075.000000   2.000000
50%     27.000000  1903.000000  1567.469136   2.000000
75%     37.500000  1928.000000  1692.500000   4.000000
max     52.000000  1986.000000  4558.000000   6.000000

Cleaning Log X

Data Analysis Conclusions
=============================================================================================================
The length depends heavily on material and type. From the data analytics, the length of bridge tracks with the design year. We see that the 'erected' and the 'length' data follows similar normal distribution pattern. The relative distribution of the percentiles track to show that the later the bridge was built, the greater the length of the bridge.

URL for This Assignmemnt's Repo
================================================================================

https://github.com/chillyvee70/cs82a-portfolio/tree/main/module_3